# Ocaml-Cgi configuration                             -*- Makefile -*-
# Copyright (C) Christophe TROESTLER
#	$Id: Makefile.config,v 1.1 2005/01/24 17:28:38 chris_77 Exp $	
#
# $(PKGNAME) and $(PKGVERSION) are defined.

# OCAMLC, OCAMLOPT, OCAMLDEP, OCAMLDOC
# The location of the OCaml compiler and tools. The defaults should be OK.
#
OCAMLC	 = ocamlc
OCAMLOPT = ocamlopt
OCAMLDEP = ocamldep
OCAMLDOC = ocamldoc
OCAMLMKLIB = ocamlmklib

# Caml header files
OCAML_H  = $(shell ocamlc -where)/caml

# LIBMAGIC location
MAGIC_H = /usr/include
MAGIC_A = /usr/lib

#PREFIX=/usr/local
PREFIX=/usr/local/stow/ocaml-$(PKGNAME)-$(PKGVERSION)

# OCAMLLIBDIR: location of OCaml's library files. The default should be OK.
#
OCAMLLIBDIR = $(PREFIX)/lib/ocaml/$(shell ocamlc -version)

# OCAMLLINSTUB: location of OCaml's stub files.
#
OCAMLLINSTUBS = $(OCAMLLIBDIR)/stublibs

# DOCDIR: where we will install the documentation.
#
DOCDIR = $(PREFIX)/doc/$(PKGNAME)-$(PKGVERSION)

# Utilities
#
COPY = cp
#COPY = copy
